version: '3'

services:
  sdbu_node:
    image: node:12-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - sdbu-network

  sdbu_db:
    image: mongo:4-xenial
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - sdbu-network

networks:
  sdbu-network:
    name: sdbu-network
    driver: bridge
