version: '3'

services:
  sdbu_node:
    image: node:12-alpine
    volumes:
      - ./app:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - sdbu-network
  sdbu_db:
    image: mongo:4-xenial
    ports:
      - '27017:27017'
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - dbdata:/data/db
    networks:
      - sdbu-network

networks:
  sdbu-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
